export const platforms = [
  { id: "spotify", image: "spotify.png", name: "Spotify" },
  { id: "apple", image: "apple-music.png", name: "Apple Music" },
  { id: "soundcloud", image: "soundcloud.png", name: "SoundCloud" },
  { id: "youtube", image: "youtube.png", name: "YouTube" },
  { id: "deezer", image: "deezer.png", name: "Deezer" },
  { id: "beatport", image: "beatport.png", name: "Beatport" },
  { id: "itunes", image: "itunes.png", name: "iTunes" },
  { id: "yandex", image: "yandex.png", name: "Yandex Music" },
  { id: "anghami", image: "anghami.png", name: "Anghami" },
  { id: "bandcamp", image: "bandcamp.png", name: "Bandcamp" },
  { id: "amazon-music", image: "amazon.png", name: "Amazon" },
  { id: "tidal", image: "tidal.png", name: "Tidal" },
  { id: "vk", image: "vk.png", name: "VKontakte" },
  { id: "napster", image: "napster.png", name: "Napster" },
  { id: "tiktok", image: "tiktok.png", name: "TikTok" },
];